---
- name: dowloading_tomcat_tarfile
  get_url:
   url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.97/bin/apache-tomcat-8.5.97.tar.gz
   dest: /home/ubuntu/opt/
   force_basic_auth: yes
- name: extract tomcat_tarfile
  command:
       cmd: tar xzvf apache-tomcat-8.5.97.tar.gz -C /opt/tomcat --strip-components=1
       creates: /opt/tomcat/LICENSE
  